### ISSUE TITLE
Error in the combined spreadsheets

### ISSUE THREAD

**Issue by kmexter** [arms-mbon/data_workspace#19]

**Comment by cedricdcc** [comment]
Can I have a hint as to where these errors all are? @kmexter

**Comment by kmexter** [comment]
darn, thought I had written that
I think it was just the one line - https://github.com/arms-mbon/data_workspace/blob/main/QualityControlledData/Combined/combined_SamplingEventData.csv row 106-108, the observatory and unit ID are wrong or not there

**Comment by kmexter** [comment]
To be more clear, currently the rows that are wrong are those from the GulfOFPiran, with the observatory cells having the arms unit names in there instead, and the arms unit cells are therefore blank in the CSV
